In [1]:
import os
import pandas as pd

pd.set_option('display.max_colwidth', 1000)

In [4]:
data = []

with open('SemEval 2025 Target Dec Release/EN/subtask-3-annotations.txt') as file:
    for line in file:
        line = line.split('\t')
        article_id = line[0]
        dominant_narrative = line[1]
        sub_narratives = line[2].strip("\n")
        ground_truth = line[3]

        data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives, 'ground_truth': ground_truth})

df = pd.DataFrame(data)

for index, row in df.iterrows():
    path = os.path.join("SemEval 2025 Target Dec Release/EN/raw-documents", row['article_id'])

    with open(path) as file:
        text = file.read()
        df.at[index, 'text'] = text

df.to_csv('SemEval 2025 Test Data/final_datasets/eng_gold_label_data.csv', index=False)

### Creating dataset for ENG docs

In [4]:
data = []

with open('SemEval 2025 Test Data/EN/subtask-3-dominant-narratives.txt') as file:
    
    for line in file:
        line = line.split('\t')

        article_id = line[0]
        dominant_narrative = line[1]
        sub_narratives = line[2].strip("\n")

        data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives})


df = pd.DataFrame(data)

for index, row in df.iterrows():
    path = os.path.join("SemEval 2025 Test Data/EN/subtask-3-documents/", row['article_id'])

    with open(path) as file:
        text = file.read()
        df.at[index, 'text'] = text

df.to_csv('SemEval 2025 Test Data/final_datasets/eng_data.csv', index=False)

### Creating dataset for HINDI docs

In [6]:
data = []

with open('SemEval 2025 Target Dec Release/HI/subtask-3-annotations.txt') as file:
    for line in file:
        line = line.split('\t')
        article_id = line[0]
        dominant_narrative = line[1]
        sub_narratives = line[2].strip("\n")
        ground_truth = line[3]

        data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives, 'ground_truth': ground_truth})

df = pd.DataFrame(data)

for index, row in df.iterrows():
    path = os.path.join("SemEval 2025 Target Dec Release/HI/raw-documents", row['article_id'])

    with open(path) as file:
        text = file.read()
        df.at[index, 'text'] = text

df.to_csv('SemEval 2025 Test Data/final_datasets/hindi_gold_label_data.csv', index=False)

In [7]:
df.head()

,article_id,dominant_narrative,sub_narratives,ground_truth,text
0,HI_368.txt,URW: Amplifying war-related fears,URW: Amplifying war-related fears: There is a real possibility that nuclear weapons will be employed,"इस लेख का प्रमुख आख्यान युद्ध में इस्तेमाल किए जाने वाले परमाणु हथियारों के डर के बारे में है। बायडेन ने यूक्रेन को बेलिस्टिक मिसाइलों का उपयोग करने की अनुमति दे दी है, जिससे रूस का गुस्सा भड़क गया है जिसके परिणामस्वरूप पुतिन को परमाणु नीति संशोधन पर हस्ताक्षर करना पड़ा है जो परमाणु युद्ध की संभावना का संकेत देता है।\n","बाइडन के कदम से भड़के पुतिन, न्यूक्लियर डॉक्ट्रिन में कहा- अगर ऐसा हुआ तो करेंगे परमाणु हमला\n\nरूस और अमेरिका के बीच अब तनाव चरम पर पहुंचने लगा है। ट्रंप के राष्ट्रपति बनने से पहले ही जो बाइडन ने एक बड़ा कदम उठाया है। उन्होंने यूक्रेन को रूस के खिलाफ अमेरिका की लंबी दूरी की बैलिस्टिक मिसाइलों के इस्तेमाल को मंजूरी दे दी है। अगर यूक्रेन इन मिसाइलों का इस्तेमाल करता है तो वह रूस के बड़े शहरों को निशाना बनाने में सक्षम होगा।\nनई न्यूक्लियर डॉक्ट्रिन को मंजूरी\nअमेरिकी राष्ट्रपति जो बाइडन के ताजा कदम से रूसी राष्ट्रपति व्लादिमीर पुतिन बेहद खफा हैं। उन्होंने मंगलवार को एक नई न्यूक्लियर डॉक्ट्रिन को मंजूरी दी है। इसके तहत अगर किसी परमाणु संपन्न देश की मिसाइल से रूस पर हमला किया जाता है तो पुतिन परमाणु हथियारों के इस्तेमाल पर विचार कर सकते हैं।\nबाइडन को रूस का जवाब\nरूस ने अमेरिकी राष्ट्रपति जो बाइडन की मंजूरी के जवाब में अपने परमाणु सिद्धांत में बदलाव किया है। परमाणु सिद्धांतों के मुताबिक रूस पर पारंपरिक मिसाइलों, ड्रोन व अन्य विमानों से किया गया हमला भी परमाणु हथियार के इस्तेमाल करने ..."
1,HI_191.txt,URW: Praise of Russia,URW: Praise of Russia: Praise of Russian President Vladimir Putin,यह परियोजना स्पष्ट रूप से रूसी राष्ट्रपति पुतिन की प्रशंसा करती है कि वह किस प्रकार भारत और प्रधान मंत्री मोदी की हालिया नीतियों की सराहना करते रहे हैं।\n,"G20 से दूर रहे पुतिन ने की मोदी की तारीफ, रूस में गिनाए गिनाए 'मेक इन ...\n\nG20 से दूर रहे पुतिन ने की मोदी की तारीफ, रूस में गिनाए गिनाए 'मेक इन इंडिया' के फायदे\nहाल ही में संपन्न हुए G-20 शिखर सम्मेलन के दौरान पीएम मोदी ने भारत-मध्य पूर्व-यूरोप इकोनॉमिक कॉरिडोर यानी IMEC का प्रस्ताव दिया था। इसपर पुतिन की तरफ से सकारात्मक प्रतिक्रिया आई है।\nरूस के राष्ट्रपति व्लादिमीर पुतिन ने भारत और प्रधानमंत्री नरेंद्र मोदी की नीतियों की जमकर तारीफ की। मंगलवार को व्लादिवोस्तोक में आयोजित एक कार्यक्रम के दौरान पुतिन ने स्वदेशी ऑटोमोबाइल का इस्तेमाल करने की बात पर जोर दिया। साथ ही उन्होंने कहा कि भारत ने पहले ही पीएम मोदी के नेतृत्व में अपनी नीतियों के जरिए उदाहरण पेश कर दिया है। इस दौरान पुतिन ने खासतौर से 'मेक इन इंडिया' को सराहा।\n8वें ईस्टर्न इकोनॉमिक फोरम में शामिल हुए पुतिन ने कहा, 'तब हमारे पास घरेलू स्तर पर तैयार कारें नहीं थीं, लेकिन अब हैं। यह सच है कि वह मर्सिडीज या ऑडी कारों की तुलना में सामान्य नजर आती हैं, जिन्हें हमने 90 के दशक में बड़ी संख्या में खरीदा था। लेकिन अब यह मुद्दा न..."
2,HI_112.txt,URW: Russia is the Victim,URW: Russia is the Victim: Russia actions in Ukraine are only self-defence,"इस रिपोर्ट में कुर्स्क पर यूक्रेनी सेना के हमले के बारे में बात की गई है. इसमें राष्ट्रपति पुतिन सहित रूसी अधिकारियों की टिप्पणियों का उल्लेख है, जो इस हमले को एक आतंकवादी कृत्य बताते हैं जो रूस को रक्षात्मक प्रतिक्रिया देने के लिए उकसा रहा है। यह रूसी क्षेत्रों पर यूक्रेन के भड़काने वाले और आतंकवादी हमलों को उजागर करते हुए रूस को पीड़ित के रूप में चित्रित करता है।\n","टैंकों और बख्तरबंद वाहनों के साथ रूसी इलाके में घुसे यूक्रेनी सैनिक, भीषण ...\n\nरूस (Russia) की सेना गुरुवार को तीसरे दिन भी यूक्रेन के सैनिकों से जूझती रहीं. यूक्रेन के सैनिकों ने कुर्स्क (Kursk) इलाके में रूसी सीमा को तोड़ दिया. रूसी अधिकारियों के मुताबिक, दो साल पुराने युद्ध में रूस पर सबसे बड़े यूक्रेनी हमलों में से एक में, लगभग 1,000 यूक्रेनी सैनिकों ने 6 अगस्त की सुबह टैंकों और बख्तरबंद वाहनों के साथ रूस की सीमा में घुसपैठ की. जो हवा में ड्रोन और भारी तोपखाने के झुंड से घिरे हुए थे.\nसुदजा (Sudzha) शहर के पास भयंकर लड़ाई की खबर है, जहां से रूस की प्राकृतिक गैस यूक्रेन में प्रवाहित होती है, जिससे यूरोप में ट्रांजिट फ्लो के अचानक बंद होने की आशंका बढ़ गई है. रूस के राष्ट्रपति व्लादिमीर पुतिन द्वारा फरवरी 2022 में यूक्रेन में अपनी सेना भेजे जाने के करीब ढाई साल बाद, यह घुसपैठ रूस के लिए एक झटका है.\nपुतिन ने यूक्रेनी हमले को 'बड़ी उकसावे वाली कार्रवाई' बताया है. क्रेमलिन के प्रति वफादार राजनीतिक दल के नेता सर्गेई मिरोनोव ने इसे 'आतंकवादी हमला' और 'अंतरराष्ट्रीय स्तर पर मान्यता ..."
3,HI_2.txt,URW: Russia is the Victim,URW: Russia is the Victim: The West is russophobic,"इस लेख का मुख्य आख्यान यह है कि पश्चिम किस प्रकार रूस विरोधी है क्योंकि वह भारत को रूस के साथ देखकर खुश नहीं है, और इसने रूस को 2022 में बने गठबंधन से भी अलग कर दिया है।\n","प्रधानमंत्री नरेंद्र मोदी की 8 और 9 जुलाई को अपनी मास्को यात्रा पर हैं, और इस दौरान वह रूसी राष्ट्रपति व्लादिमीर पुतिन के साथ शिखर बैठक में शामिल हुए। रूस-यूक्रेन युद्ध के चलते यह एक ऐसी तस्वीर है जो पश्चिमी देश देखना नहीं चाहते। मोदी ने अपने तीसरे कार्यकाल की पहली द्विपक्षीय यात्रा के लिए रूस को चुना है, और यह पश्चिमी नेताओं के लिए एक महत्वपूर्ण संकेत है जो यूरोप में अस्थिरता के बीच इस यात्रा को लेकर चिंतित हैं।\nपश्चिम के लिए संदेश\nपुतिन को अमेरिका के नेतृत्व वाले पश्चिमी गठबंधन द्वारा 2022 में यूक्रेन पर आक्रमण के बाद से वर्जित, प्रतिबंधित और अलग-थलग कर दिया गया है। यह 2021 के बाद पहली भारत-रूस शिखर बैठक है और यूक्रेन पर रूसी आक्रमण के बाद मोदी की मास्को में पुतिन से पहली मुलाकात है। यह संदेश पश्चिम को स्पष्ट है कि भारत अपनी रणनीतिक स्वतंत्रता को बनाए रखने के लिए प्रतिबद्ध है।\nभारत-अमेरिका संबंध: मजबूती और चुनौतियां\nविशेष संबंधों के बावजूद, भारत और अमेरिका के बीच कुछ मुद्दों पर तनाव है। अमेरिका को इंडो-पैसिफिक में भारत की जरूरत है, और भारत को व्यापार और रक्षा प्रौद्योगिकी के ..."
4,HI_279.txt,URW: Speculating war outcomes,none,"इस रिपोर्ट का मुख्य उद्देश्य पश्चिम के युद्ध परिणामों की अटकलों को चित्रित करना है यदि वे यूक्रेन के अनुरोध पर सहमत होते हैं और दूरगामी मिसाइलें भेजते हैं जो रूस में प्रवेश कर सकती हैं और नष्ट कर सकती हैं। नाटो देशों और पश्चिम के लिए पुतिन की खुली धमकी का उल्लेख किया गया है, साथ ही अमेरिकी राष्ट्रपति और ब्रिटिश प्रधान मंत्री के बीच उनकी कार्रवाई के अगले कदम पर निर्णय लेने के लिए बैठक का भी उल्लेख किया गया है।\n","पुतिन की धमकी के बाद लंबी दूरी की मिसाइलों पर अमेरिका-ब्रिटेन की बैठक, क्या बनी बात?\n\nब्रिटेन और अमेरिका ने यूक्रेन को रूस के अंदर तक मार करने वाली लंबी दूरी की मिसाइलों की इजाज़त देने पर कोई फ़ैसला नहीं किया है.\nब्रिटिश प्रधानमंत्री सर कीएर स्टार्मर और अमेरिकी राष्ट्रपति जो बाइडन के बीच वॉशिंगटन में शुक्रवार को हुई मुलाक़ात में इस बात पर कोई फ़ैसला नहीं हुआ, ना ही पीएम स्टार्मर ने इस बारे में कोई संकेत दिया.\nपीएम स्टार्मर से पूछा गया कि क्या उन्होंने रूस के अंदर लंबी दूरी तक मार करने वाली स्टॉर्म शैडो मिसाइल के इस्तेमाल की यूक्रेन को इजाज़त दिए जाने को लेकर बाइडन को सहमत कराने की कोशिश की थी?\nइस पर उन्होंने कहा कि कई मोर्चों पर उनके बीच “लंबी और सफल बातचीत रही, जिसमें यूक्रेन, मध्य पूर्व और हिंद प्रशांत का मुद्दा भी शामिल था.”\nहालांकि व्हाइट हाउस ने कहा है कि रूस को ईरान और उत्तर कोरिया से मिलने वाले घातक हथियारों को लेकर उसने गहरी चिंता व्यक्त की है.\nइससे पहले रूस के राष्ट्रपति व्लादिमीर पुतिन ने पश्चिमी देशों को चेतावनी दी थी कि 'वे रूस पर हमला करने के लिए यूक्रेन को लंबी..."

### Create Bulgarian Gold Dataset

In [9]:
data = []

with open('SemEval 2025 Target Dec Release/BG/subtask-3-annotations.txt') as file:
    for line in file:
        line = line.split('\t')
        article_id = line[0]
        dominant_narrative = line[1]
        sub_narratives = line[2].strip("\n")
        ground_truth = line[3]

        data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives, 'ground_truth': ground_truth})

df = pd.DataFrame(data)

for index, row in df.iterrows():
    path = os.path.join("SemEval 2025 Target Dec Release/BG/raw-documents", row['article_id'])

    with open(path) as file:
        text = file.read()
        df.at[index, 'text'] = text

df.to_csv('SemEval 2025 Test Data/final_datasets/bulgarian_gold_label_data.csv', index=False)

In [10]:
df.shape

(357, 5)

### Create Portuguese Gold Label Dataset

In [11]:
data = []

with open('SemEval 2025 Target Dec Release/PT/subtask-3-annotations.txt') as file:
    for line in file:
        line = line.split('\t')
        article_id = line[0]
        dominant_narrative = line[1]
        sub_narratives = line[2].strip("\n")
        ground_truth = line[3]

        data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives, 'ground_truth': ground_truth})

df = pd.DataFrame(data)

for index, row in df.iterrows():
    path = os.path.join("SemEval 2025 Target Dec Release/PT/raw-documents", row['article_id'])

    with open(path) as file:
        text = file.read()
        df.at[index, 'text'] = text

df.to_csv('SemEval 2025 Test Data/final_datasets/portuguese_gold_label_data.csv', index=False)

In [12]:
df.shape

(252, 5)

### Create Russian Gold Label Dataset

In [13]:
data = []

with open('SemEval 2025 Target Dec Release/RU/subtask-3-annotations.txt') as file:
    for line in file:
        line = line.split('\t')
        article_id = line[0]
        dominant_narrative = line[1]
        sub_narratives = line[2].strip("\n")
        ground_truth = line[3]

        data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives, 'ground_truth': ground_truth})

df = pd.DataFrame(data)

for index, row in df.iterrows():
    path = os.path.join("SemEval 2025 Target Dec Release/RU/raw-documents", row['article_id'])

    with open(path) as file:
        text = file.read()
        df.at[index, 'text'] = text

df.to_csv('SemEval 2025 Test Data/final_datasets/russian_gold_label_data.csv', index=False)

In [14]:
df.shape

(133, 5)

### Create Test Dataset

In [3]:
import os
import pandas as pd

source = '/Users/rahulbouri/Downloads/SemEval 2025 Test Data'

for item in os.listdir(source):
            
    if item is '.DS_Store':
        continue

    if os.path.isdir(os.path.join(source, item)):

        data = []

        with open(f'/Users/rahulbouri/Downloads/SemEval 2025 Test Data/{item}/subtask-3-dominant-narratives.txt') as file:
            for line in file:
                line = line.split('\t')
                article_id = line[0]
                dominant_narrative = line[1]
                sub_narratives = line[2].strip("\n")
                data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives})

        df = pd.DataFrame(data)

        for index, row in df.iterrows():
            path = os.path.join(f"/Users/rahulbouri/Downloads/SemEval 2025 Test Data/{item}/subtask-3-documents", row['article_id'])

            with open(path) as file:
                text = file.read()
                df.at[index, 'text'] = text

        df.to_csv(f'/Users/rahulbouri/Downloads/SemEval 2025 Test Data/{item}_test_data.csv', index=False)

<>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
/var/folders/wc/g01grcxj65z_db1mfdrp2l140000gn/T/ipykernel_24176/2347967424.py:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if item is '.DS_Store':

### Submission Files

In [1]:
import pandas as pd

In [20]:
df = pd.read_csv('/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/dev_set_subs/eng_dev_predictions(1).csv')
df = df.astype(str)
df.head()

,article_id,dominant_narrative,sub_narratives,text,mode,output_temp_0.3
0,EN_UA_DEV_100012.txt,"URW: Discrediting the West, Diplomacy","URW: Discrediting the West, Diplomacy: The Wes...",Ukraine's Minerals: What the West is Fighting ...,URW,"The dominant narrative of ""Discrediting the We..."
1,EN_CC_200040.txt,CC: Criticism of climate movement,none,Climate Protesters Out Of Control As They Atta...,CC,"The dominant narrative of ""Criticism of climat..."
2,EN_CC_200070.txt,CC: Criticism of institutions and authorities,CC: Criticism of institutions and authorities:...,Wat? L.A. Mayor Garcetti Flies to Argentina to...,CC,"The dominant narrative of ""Criticism of instit..."
3,EN_UA_DEV_100034.txt,URW: Overpraising the West,URW: Overpraising the West: The West belongs i...,Opinion: Restructuring Ukrainian debt is a ste...,URW,"The dominant narrative ""Overpraising the West""..."
4,EN_CC_200049.txt,CC: Questioning the measurements and science,none,Alarmists Warn of U.S. ‘Heat Dome’ Tied to Hum...,CC,"The dominant narrative of ""Questioning the mea..."

In [22]:
with open("/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/dev_set_subs/eng_dev_subtask3(1).txt", "w") as f:
    for idx, row in df.iterrows():
        article_id = row['article_id']
        output = row['output_temp_0.3']
        f.write(f"{article_id}\t{output}\n")

In [11]:
import os

data = []

with open('/Users/rahulbouri/Downloads/dev-documents_4_December/EN/subtask-3-dominant-narratives.txt') as file:
    for line in file:
        line = line.split('\t')
        article_id = line[0]
        dominant_narrative = line[1]
        sub_narratives = line[2].strip("\n")

        data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives})

df = pd.DataFrame(data)

for index, row in df.iterrows():
    path = os.path.join("/Users/rahulbouri/Downloads/dev-documents_4_December/EN/subtask-3-documents", row['article_id'])

    with open(path) as file:
        text = file.read()
        df.at[index, 'text'] = text

df.to_csv('/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/dev_set_subs/eng_dev_subtask3.csv', index=False)

In [19]:
import os

data = []

with open('/Users/rahulbouri/Downloads/dev-documents_4_December/PT/subtask-3-dominant-narratives.txt') as file:
    for line in file:
        line = line.split('\t')
        article_id = line[0]
        dominant_narrative = line[1]
        sub_narratives = line[2].strip("\n")

        data.append({'article_id': article_id, 'dominant_narrative': dominant_narrative, 'sub_narratives': sub_narratives})

df = pd.DataFrame(data)

for index, row in df.iterrows():
    path = os.path.join("/Users/rahulbouri/Downloads/dev-documents_4_December/PT/subtask-3-documents", row['article_id'])

    with open(path) as file:
        text = file.read()
        df.at[index, 'text'] = text

df.to_csv('/Users/rahulbouri/Desktop/task10.2/subtask3/SemEval 2025 Test Data/dev_set_subs/portuguese_dev_subtask3.csv', index=False)